@startuml prebid_td_context

title Prebid: contextual selection process

participant User
participant "pub.com" as Pub
participant "prebid.js" as Pbjs
participant SSPs
participant DSPs
participant "gam.js" as Gmjs
participant "GAM/AdX" as Gam

User -> Pub: 1. navigates browser to pub.com
activate Pub
Pub -> Pbjs: 2. load, configure, execute prebid.js
activate Pbjs
Pbjs -> SSPs: 3. make contextual ad requests
activate SSPs
SSPs -> SSPs: 4. traffic quality controls
SSPs -> DSPs: 5. make contextual bid requests 
activate DSPs
SSPs <- DSPs: 6. respond with contextual bids
deactivate DSPs
SSPs -> SSPs: 7. pub ad controls
Pbjs <- SSPs: 8. respond with contextual ads
deactivate SSPs
Pbjs -> Pbjs: 9. store contextual bids/creatives
Pbjs -> Gmjs: 10. configure k/v pair for ad tag
activate Gmjs
Pub <- Pbjs: 11. wait for ad slot to load
deactivate Pbjs

note over Pub, Gmjs
At this point control over the ad loading process is transferred from Prebid to GAM
end note

Pub -> Gmjs: 12. load slot
Gmjs -> Gam: 13. contextual ad request
activate Gam
Gmjs <- Gam: 14. respond with winning contextual ad
deactivate Gam
Pub <- Gmjs: 15. contextual ad/bid available
deactivate Gmjs

note over Pub, Gmjs
All contextual bids are now in the page. Any IG bids are resident in browser. Now the final selection process must take place.
end note

deactivate Pub
@enduml