@startuml prebid_pk_interest

title Prebid: interest bid selection and final decision

participant User
participant "pub.com" as Pub
participant "prebid.js" as Pbjs
participant "Edge" as Edge
participant "Parakeet" as Pk
participant "Prebid Server" as Pbs
participant "Exchanges" as Ex
participant "Dsps" as Dsp

activate Pub
Pub -> Pbjs: 1. begin final ad selection

activate Pbjs
Pbjs -> Pbjs: 2. select contextual winner
activate Edge
Pbjs -> Edge: 3: navigator.createAdRequest

activate Pk
Edge -> Pk: 4. anonymized interests + full contextual data
activate Pbs
Pk -> Pbs: 5. anonymized interestes + sanitized contextual data
activate Ex
Pbs -> Ex: 6. OpenRTB ad request
activate Dsp
Ex -> Dsp: 7. bid requests
Ex <- Dsp: 8. bids
deactivate Dsp
Pbs <- Ex: 9. winning exchange bid
deactivate Ex
Pbs <- Pbs: 10. chooses winning IG bid
Pk <- Pbs: 11. winning bid
deactivate Pbs
Pk <- Pk: 12. compares best bid with contextual ad
Edge <- Pk: 13. winning ad
deactivate Pk
Pbjs <- Edge: 14. token/false

alt IG bid winner
    Edge -> Pbjs: 15.1 opaque object
    deactivate Edge
    Pbjs -> Pbjs: 15.2. record IG win
    Pbjs -> Pbjs: 15.3. render IG ad
else contextual ad winner
    Edge -> Pbjs: 16.1 false
    deactivate Edge
    Pbjs -> Pbjs: 16.2. render contextual ad
    Pbjs -> Pbjs: 16.3. record contextual win
Pub <- Pbjs: 17. ad rendered
deactivate Pbjs

User <- Pub

deactivate Pub
@enduml

