@startuml prebid_td_context

title Prebid: contextual selection process

participant User
participant "pub.com" as Pub
participant "prebid.js" as Pbjs
participant "prebid_[SSP_MODULE].js" as PbSspjs
participant SSPs
participant DSPs
participant "gam.js" as Gmjs
participant "GAM/AdX" as Gam

User -> Pub: 1. navigates browser to pub.com
activate Pub
Pub -> Pbjs: 2. load, configure, execute prebid.js
activate Pbjs
Pbjs -> PbSspjs: 3. invoke SSP bid adapter
activate PbSspjs
PbSspjs -> SSPs: 4. contextual ad request
activate SSPs
SSPs -> SSPs: 5. traffic quality controls
SSPs -> DSPs: 6. make contextual bid requests 
activate DSPs
SSPs <- DSPs: 7. respond with contextual bids
deactivate DSPs
SSPs -> SSPs: 8. pub ad controls
PbSspjs <- SSPs: 9. ad w/price
deactivate SSPs
Pbjs <- PbSspjs: 10. ad w/price
deactivate PbSspjs

Pbjs -> Pbjs: 11. select appropriate contextual ad
Pbjs -> Gmjs: 12. configure k/v pair for selected contextual ad
activate Gmjs
Pub <- Pbjs: 13. wait for ad slot to load
deactivate Pbjs

note over Pub, Gmjs
At this point control over the contextual ad loading process is transferred from Prebid.js to GAM
end note

Pub -> Gmjs: 14. load slot
Gmjs -> Gam: 15. contextual ad request
activate Gam
Gmjs <- Gam: 16. respond with winning contextual ad, which may be prebid.js line item
deactivate Gam

note over Pub, Gmjs
All contextual bids are now in the page. Any IG bids are resident in browser. Now the final selection process must take place.
end note


Pub <- Gmjs: 17. contextual ad/bid available
deactivate Gmjs

deactivate Pub
@enduml